Feature/3536 upload video immediately to stream
utu-technologies/react-media-recorder pull request #3
Opened 2021-04-30 09:38 UTC by kimiti

2021-05-05 10:33 UTC, ivan-apeunit requested changes

2021-05-05 10:33 UTC, ivan-apeunit commented on package.json
> -    "prepublishOnly": "npm run build"
Let leave both (prepublishOnly and prepare). prepublishOnly is needed for backward compatibility, if we want to merge with original repo

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +  reset(): void | null;
void | null - return contract is not clear.
void - no value is returned.
null - returned in case some values were not found or do not exist

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +  onStop?: (blobUrl: string | null, blob: Blob | null) => void;
The previous args types seem to be right. If it should be blobUrl or blob, I would suggest `| undefined` instead.

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +class uploadStorageStrategy implements VideoStorage {
It's weird to inherit Strategy from Storage. Set the proper name to align interface and class because they are not consistent now.

There is a convention to start interface name with "I", like IStraregy or IStorage. Please check, if this convention should be followed here as well.

The class name should start with a capital letter.

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +  blobProperties: any;
Which of those properties should be private?

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +    let blob = new Blob(this.mediaChunks, this.blobProperties);
const instead of let

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +    let blob = new Blob(this.mediaChunks, this.blobProperties);
Or just set directly to this.blob and this.url

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +    this.mediaChunks = [];
this.url = null missing

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +    let blobPropertiesState: Boolean = false;
= false already defines type as Boolean, so : Boolean is not needed

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +    if (!blobPropertiesState) {
It is equal to `if (!false) `all the time

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +        { type: data.type },
Should be refactored. It's hard to understand why type = data.type, and then overridden with video/mp4 or audio/wav

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +    return this.url;
return null?

2021-05-05 10:33 UTC, ivan-apeunit commented on src/index.ts
> +    return null;
Shouldn't you merge chunks here?

2021-05-06 13:56 UTC, databu commented on src/index.ts
> +  reset(): void | null;
@kimiti this was already correct in a previous version, please revert to it:
```
export interface VideoStorage {
  /** Sets blob properties. This will be called only before the first call of storeChunk() after construction or reset(). */
  setBlobProperties(blobProperties: BlobPropertyBag): void;

  /** Handle recorded video chunk. */
  storeChunk(chunk: Blob): void;

  /** Informs this storage that the last chunk has been provided. */
  stop(): void;

  /** Resets this storage so that a new video can be recorded. */
  reset(): void;

  /** Gets the URL where the video is stored. */
  getUrl(): string | null;

  /** If this storage stores all chunks in a merged Blob, returns it; otherwise returns undefined.*/
  getBlob(): Blob | undefined;
}
```

2021-05-20 12:34 UTC, closed without merging